name = "theparanormalinitiative"
compatibility_date = "2026-07-18"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[assets]
directory = "."

[[d1_databases]]
binding = "TPI_DB"
database_name = "tpi_contributor_portal"
database_id = "REPLACE_WITH_CLOUDFLARE_D1_DATABASE_ID"
